[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  # Disable Next.js telemetry
  NEXT_TELEMETRY_DISABLED = "1"
  # Force fresh builds
  NODE_ENV = "production"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Handle API routes properly
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Essential Next.js redirects
[[redirects]]
  from = "/_next/static/*"
  to = "/static/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Role = ["admin"]}