#!/bin/bash

echo "📦 Your JAde Wii Music Store is ready to deploy!"
echo ""
echo "To push to GitHub, follow these steps:"
echo ""
echo "1. First, create a new repository on GitHub:"
echo "   👉 Go to: https://github.com/new"
echo "   - Repository name: music-store"
echo "   - Description: JAde Wii Music Store"
echo "   - Keep it PUBLIC"
echo "   - DON'T initialize with README, .gitignore, or license"
echo "   - Click 'Create repository'"
echo ""
echo "2. Then run these commands:"
echo ""
echo "   git remote add origin https://github.com/jadewii/music-store.git"
echo "   git push -u origin main"
echo ""
echo "3. When prompted for authentication:"
echo "   - Username: jadewii"
echo "   - Password: Use a Personal Access Token (not your password)"
echo "   - To create a token: GitHub Settings → Developer settings → Personal access tokens"
echo ""
echo "Your code is already committed and ready to push!"
echo "Current commit: $(git log -1 --oneline)"
echo ""
echo "After pushing, you can deploy to Vercel:"
echo "👉 https://vercel.com/new"